---
title: "plot_model"
author: "Luke Holman"
date: "2018-07-17"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r setup, echo=FALSE, results='hide'}
source_rmd <- function(file, local = FALSE){
  options(knitr.duplicate.label = "allow")
  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  print(file.exists("model_functions.Rmd"))
  knitr::purl(file, output = tempR, quiet = TRUE)
  source(tempR, local = globalenv())
}
source_rmd("analysis/model_functions.Rmd")
```

# Load packages and results

```{r}
library(ggplot2)
library(ggbeeswarm)
library(gridExtra)
# library(brms)
library(ggeffects)
library(readr)
library(gridExtra)
library(grid)
library(pander)
library(latex2exp)
library(Cairo)
library(car)


if(!file.exists("data/all_results.rds")){
  results <- lapply(list.files(path = "data", pattern = "results_", full.names = T), readRDS) %>% 
    do.call("rbind", .)
  saveRDS(results, file = "data/all_results.rds")
} else results <- read_rds("data/all_results.rds")

results$went_extinct <- ifelse(results$outcome == "Population extinct", 1, 0)

results$migration_type[results$migration_type == "local"] <- "Local"
results$migration_type[results$migration_type == "global"] <- "Global"

variable_parameters <- sapply(
  results %>% 
    select(-id, -realisations, -generation_extinct, -generation_Zd_extinct, -generation_W_extinct, -generation_Zd_fixed, -outcome, -went_extinct, -mating_table, -initial_Wr, -initial_Zr), 
  function(x) length(unique(x))) %>% 
  keep(~.x > 1) %>% names()

nice_names <- data.frame(original = variable_parameters,
                         new = gsub("_", " ", variable_parameters),
                         stringsAsFactors = FALSE) %>%
  mutate(
    new = gsub("rel", "Rel", new),
    new = gsub("W shredding rate", "Gene drive in females ($p_{shred}$)", new),
    new = gsub("Z conversion rate", "Gene drive in males ($p_{conv}$)", new),
    new = gsub("Zr creation rate", "Rate of NHEJ ($p_{nhej}$)", new),
    new = gsub("Zr mutation rate", "Z-linked resistance ($\\mu{_Z}$)", new),
    new = gsub("Wr mutation rate", "W-linked resistance ($\\mu{_W}$)", new),
    new = gsub("cost Zdrive female", "Cost of Z* to females ($c_f$)", new),
    new = gsub("cost Zdrive male", "Cost of Z* to males ($c_m$)", new),
    new = gsub("male migration prob", "Male dispersal frequency", new),
    new = gsub("feMale dispersal frequency", "Female dispersal frequency (xf)", new),
    new = gsub("Male dispersal frequency", "Male dispersal frequency (xm)", new),
    new = gsub("xm", "$x_m$", new), 
    new = gsub("xf", "$x_f$", new),
    new = gsub("migration type", "Dispersal type", new),
    new = gsub("n patches", "Number of patches ($k$)", new),
    new = gsub("softness", "Importance of local density ($\\psi$)", new),
    new = gsub("male weighting", "Male effect on density ($\\delta$)", new),
    new = gsub("density dependence shape", "Shape of density dependence ($\\alpha$)", new),
    new = gsub("max fecundity", "Maximum fecundity ($r$)", new),
    new = as.character(TeX(new))
  ) %>% mutate(
    new = gsub("mu", "\\mu", new)
  )

```

## Table showing the frequencies of each possible outcome
```{r}
outcomes <- results$outcome %>% table() %>% melt() %>% arrange(-value) 
names(outcomes) <- c("Outcome", "Number of simulations")
outcomes %>% mutate(Outcome = gsub("without", "without causing", Outcome),
                    Outcome = gsub("n extinct", "n went extinct", Outcome),
                    Outcome = gsub("d extinct", "d went extinct", Outcome)) %>% pander()
```

## Statistical model

Run a binomial generalized linear model with each variable parameter, and all the possible 2-way interactions among them, as predictors. The response variable is 

```{r}
if(!file.exists("data/anova_results.rds")){
  form <- as.formula(
    paste("went_extinct ~ (",
          paste0(variable_parameters, collapse = " + "), ")^2 - W_shredding_rate:cost_Zdrive_female",
          sep = ""))
  glm_model <- glm(form, data = results, family = "binomial")
  anova_results <- list(glm_model, Anova(glm_model, type = "III"))
  write_rds(anova_results, "data/anova_results.rds")
} else anova_results <- read_rds("data/anova_results.rds")
```


```{r}
get_percent_extinct <- function(parameter){
  results %>%
    group_by(!! sym(parameter)) %>%
    summarise(extinct = sum(went_extinct),
              not_extinct = n() - sum(went_extinct),
              prob = list(binom.test(extinct, extinct + not_extinct))) %>%
    rowwise() %>%
    mutate(percent_extinct = 100 * extinct/(extinct + not_extinct),
           lower_95_CI = 100 * prob$conf.int[1],
           upper_95_CI = 100 * prob$conf.int[2],
           parameter =  parameter) %>% rename(value = !! sym(parameter)) %>%
    select(parameter, value, everything()) %>% select(-prob) %>% ungroup()
} 
percent_extinct <- lapply(variable_parameters, get_percent_extinct) %>% do.call("rbind", .)

parameter_importance <- percent_extinct %>%
  mutate(parameter = nice_names$new[match(parameter, nice_names$original)]) %>%
  group_by(parameter) %>% summarise(range = max(percent_extinct) - min(percent_extinct)) %>%
  arrange(-range) %>% pull(parameter)

levels <- levels(factor(percent_extinct$value))
levels <- c(levels[!(levels %in% c("all_patches", 100))], 100, "all_patches")
levels <- replace(levels, levels == "all_patches", "Release in\nall patches")
levels <- replace(levels, levels == "one_patch", "Release in\na single patch")



cairo_pdf(file = "figures/figure2.pdf", width = 10, height = 10)
percent_extinct %>% 
  mutate(parameter = nice_names$new[match(parameter, nice_names$original)],
         parameter = factor(parameter, parameter_importance),
         value = replace(value, value == "all_patches", "Release in\nall patches"),
         value = replace(value, value == "one_patch", "Release in\na single patch"),
         value = factor(value, levels)) %>%
  ggplot(aes(value, percent_extinct)) + 
  geom_errorbar(aes(ymin=lower_95_CI, ymax = upper_95_CI), width = 0) +
  geom_point() + 
  facet_wrap(~parameter, scales = "free", labeller = label_parsed) + 
  xlab("Parameter value") +
  ylab("% simulation runs resulting in extinction") + 
  theme_bw() + 
  theme(strip.background = element_blank(),
        panel.grid.major.x = element_blank())
dev.off()

```


```{r}
get_percent_extinct_double <- function(p1, p2){
  output <-  results %>%
    group_by(!! sym(p1), !! sym(p2)) %>%
    summarise(extinct = sum(went_extinct),
              not_extinct = n() - sum(went_extinct),
              prob = list(binom.test(extinct, extinct + not_extinct))) %>%
    rowwise() %>%
    mutate(percent_extinct = 100*extinct/(extinct+not_extinct),
           lower_95_CI = 100*prob$conf.int[1],
           upper_95_CI = 100*prob$conf.int[2],
           parameter_1 =  p1, 
           parameter_2 =  p2) 
  names(output)[1:2] <- paste("value", 1:2, sep = "_")
  output %>%
    mutate(value_1 = as.character(value_1), value_2 = as.character(value_2)) %>%
    select(parameter_1, parameter_2, value_1, value_2, everything()) %>% 
    select(-prob) %>% ungroup()
} 
combinations <- combn(variable_parameters, 2)
two_way <- map2_df(combinations[1, ], combinations[2, ], get_percent_extinct_double)

two_way_plot <- function(pairwise_combos){
  split_data <- two_way %>%
    mutate(percent_extinct = percent_extinct - mean(percent_extinct)) 
  z_range <- range(split_data$percent_extinct) * 1.1
  
  make_one <- function(df){
    xlab <- df$parameter_1[1]
    ylab <- df$parameter_2[1]
    ggplot(df, aes(value_1, value_2, fill = percent_extinct)) + 
      geom_tile(colour = "black") + 
      scale_fill_distiller(palette = "RdYlBu") + 
      xlab(xlab) + ylab(ylab) + 
      theme_minimal() + 
      scale_x_discrete(expand = c(0,0)) + 
      scale_y_discrete(expand = c(0,0)) 
  }
  
  grid_arrange_shared_legend <- function(...) {
    plots <- list(...)
    g <- ggplotGrob(plots[[1]] + theme(legend.position="bottom"))$grobs
    legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
    lheight <- sum(legend$height)
    grid.arrange(
      do.call(arrangeGrob, lapply(plots, function(x)
        x + theme(legend.position="none"))),
      legend,
      ncol = 1,
      heights = unit.c(unit(1, "npc") - lheight, lheight))
  }
  
  split_data %>%
    filter(paste(parameter_1, parameter_2, sep="~") %in% pairwise_combos) %>% 
    split(paste(.$parameter_1, .$parameter_2)) %>% 
    lapply(make_one) %>% do.call("grid_arrange_shared_legend", .)
}

split_combos <- apply(t(combinations), 1, paste0, collapse = "~")
split_combos <- split(split_combos, ceiling(seq_along(split_combos)/30))

two_way_plot(split_combos[[1]])
two_way_plot(split_combos[[2]])
two_way_plot(split_combos[[3]])
two_way_plot(split_combos[[4]])
two_way_plot("n_patches~softness")


anova_results %>% rownames_to_column("Parameter") %>% 
  arrange(`LR Chisq`) %>% filter(`Pr(>Chisq)` < 0.05) %>%
  mutate(Parameter = gsub(":", " x ", Parameter),
         Parameter = factor(Parameter, Parameter)) %>%
  ggplot(aes(Parameter, `LR Chisq`)) + 
  geom_bar(stat = "identity") + 
  coord_flip()

# glm_model %>% ggpredict() %>% do.call("bind_rows", .)

# brms_model <- brm(form, 
#     data = results, 
#     family = "bernoulli", inits = "0",
#     iter = 8000, warmup = 4000, chains = 4, cores = 4, seed = 1,
#     control = list(adapt_delta = 0.9, max_treedepth = 15)
#     ) 
```

```{r}
a <- read_rds("data/allele_freqs_1.rds")

df <- a[as.character(results$id[1])][[1]]

plot_run <- function(allele_freqs_list, model_id){
  
  df <- pluck_allele_freqs(allele_freqs_list, model_id) 
  
  alleles_to_plot <- group_by(df, allele) %>% 
    summarise(uniques = length(unique(frequency))) %>% 
    filter(uniques > 1) %>% # Don't plot alleles that stay at 0 whole time
    pull(allele)
  
  df$frequency[df$allele == "N"] <- df$frequency[df$allele == "N"] /
    max(df$frequency[df$allele == "N"])
  
  paras <- results %>% mutate(id = as.character(id)) %>% filter(id == model_id)
  last_generation <- tail(df,12) %>% select(allele, frequency)
  print(paras); print(last_generation)

  ggplot(df[df$allele %in% alleles_to_plot, ], 
         aes(x = generation, y = frequency, colour = allele, group = allele)) + 
    geom_line()
}
results$id[results$went_extinct == 1 & results$id %in% names(a)][2]) %>% plot_run(a)
results$id[results$went_extinct == 1 & results$id %in% names(a)][4]) %>% plot_run(a)
results$id[results$went_extinct == 1 & results$id %in% names(a)][5]) %>% plot_run(a)

results$id[results$went_extinct == 1 & results$Zr_creation_rate == 0.1 & results$id %in% names(a)][2] %>% plot_run(a)

```



```{r}
plot_data <- pluck(results, "generation_extinct") %>%
  add_parameters() %>% select(-id) %>% remove_nonvariable_parameters() %>%
  mutate(not_extinct = is.na(generation_extinct),
         generation_extinct = replace(generation_extinct,
                                      not_extinct,
                                      rnorm(length(generation_extinct[not_extinct]),
                                            mean = 1000, sd = 0))) # change later?

plot_data %>%
  ggplot(aes(factor(Zr_creation_rate), generation_extinct, fill = not_extinct)) +
  geom_beeswarm(shape = 21, colour = "black", cex = 2, aes(alpha = Zr_creation_rate)) +
  facet_grid(female_migration_prob~softness) +
  # stat_summary(data = dat %>%
  #                filter(!not_extinct),
  #              fun.data = "mean_cl_boot", shape = 21, fill = "white") +
  theme(legend.position = "top")
```


```{r}
pop_size_results <- results %>% 
  pluck("allele_freqs") %>% 
  filter(allele == "N") %>% 
  add_parameters() %>% select(-allele) %>% 
  rename(pop_size = frequency)

pop_size_results %>%
  ggplot(aes(generation, pop_size, group = id)) +
  geom_line() +
  facet_grid(Zr_creation_rate ~ softness)
```

```{r}
max_N <- max(pluck(results, "allele_freqs")$frequency, na.rm = T)

pluck(results, "allele_freqs") %>%
  add_parameters() %>%
  filter(allele %in% c("Zd")) %>%
  # mutate(frequency = unlist(modify_at(frequency, which(allele == "N"), ~./max_N))) %>%
  ggplot(aes(generation, frequency, group = id, colour = allele)) +
  geom_line() +
  facet_grid(Zr_creation_rate ~ softness) +
  scale_x_continuous(limits = c(0,350))
```

# problem in para2, Wr appears when it should not?
```{r}
foc <- 2
df <- pluck(results, "allele_freqs") %>% filter(id == foc) 
pop <- df %>% filter(allele == "N")
df <- df %>% filter(!(allele %in% c("A", "B", "Z", "W", "N")))
grid.arrange(ggplot(df, aes(generation, frequency, colour = allele)) + 
               geom_line() + 
               scale_color_brewer(palette = "Pastel1") + theme_black(),
             ggplot(pop, aes(generation, frequency/1000, colour = allele)) + 
               geom_line() + ylab("Pop size (1000s)") +
               theme_black())
pluck(results, "parameters") %>% filter(id == foc) 
```

